name: trusir
description: "TRUSIR EDUCATION."
publish_to: "none"

version: 1.0.0+7

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  intl_phone_number_input:
  http:
  dio:
  path_provider:
  permission_handler:
  package_info_plus:
  flutter_svg:
  url_launcher:
  device_info_plus:
  shared_preferences:
  image_picker:
  intl:
  table_calendar:
  flutter_local_notifications:
  open_file:
  signature:
  path:
  video_player:
  animated_splash_screen:
  chewie:
  google_fonts:
  youtube_player_flutter:
  phonepe_payment_sdk:
  crypto:
  flutter_image_compress:
  multi_select_flutter:
  hexcolor:
  connectivity_plus:
  image:
  photo_view:
  rename:
  firebase_core:
  firebase_auth:
  firebase_app_check:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_colorpicker: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
