// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjThGUYm98YtypGzwPP3C8CKsvnqjFx4k',
    appId: '1:1017485472778:web:dd1e4eb1719f0e04e75bf3',
    messagingSenderId: '1017485472778',
    projectId: 'trusir-903a1',
    authDomain: 'trusir-903a1.firebaseapp.com',
    storageBucket: 'trusir-903a1.firebasestorage.app',
    measurementId: 'G-YVN5LKFJJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANean2Y_TDZbUet9S7NfCxYDpmTyghm5k',
    appId: '1:1017485472778:android:d21942a88fe0298be75bf3',
    messagingSenderId: '1017485472778',
    projectId: 'trusir-903a1',
    storageBucket: 'trusir-903a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXtMkP31KKEEAK2maqTvUl-G_1rKWyHtk',
    appId: '1:1017485472778:ios:3d748e52c2adf5b8e75bf3',
    messagingSenderId: '1017485472778',
    projectId: 'trusir-903a1',
    storageBucket: 'trusir-903a1.firebasestorage.app',
    androidClientId: '1017485472778-l9g1anqv76f0erc14vdmns8age19hbur.apps.googleusercontent.com',
    iosBundleId: 'com.trusir.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXtMkP31KKEEAK2maqTvUl-G_1rKWyHtk',
    appId: '1:1017485472778:ios:e23e29ed269a5855e75bf3',
    messagingSenderId: '1017485472778',
    projectId: 'trusir-903a1',
    storageBucket: 'trusir-903a1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjThGUYm98YtypGzwPP3C8CKsvnqjFx4k',
    appId: '1:1017485472778:web:f3d381a42f8b9b18e75bf3',
    messagingSenderId: '1017485472778',
    projectId: 'trusir-903a1',
    authDomain: 'trusir-903a1.firebaseapp.com',
    storageBucket: 'trusir-903a1.firebasestorage.app',
    measurementId: 'G-GFK8Q4479B',
  );
}